

if(CONFIG_DRIVER_RTC_DS1302)
    set_property(GLOBAL APPEND PROPERTY DRVFX_DRIVERS_SOURCES "ds1302.c")
endif()

if(CONFIG_DRIVER_RTC_PCF8563)
    set_property(GLOBAL APPEND PROPERTY DRVFX_DRIVERS_SOURCES "pcf8563.c")
endif()

if(CONFIG_DRIVER_RTC_IDF)
    set_property(GLOBAL APPEND PROPERTY DRVFX_DRIVERS_SOURCES "idf.c")
endif()