name: Flutter CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          channel: stable
          flutter-version: 3.27.0

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: flutter pub get

      - name: Run dart format check
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: melos run test:all

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          cache: true
          channel: stable
          flutter-version: 3.27.1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/borneo-app-release.apk
