name: Borneo Firmware CI

on:
  push:
    branches: [master, dev]
    paths:
      - 'fw/**'
  pull_request:
    branches: [master, dev]
    paths:
      - 'fw/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build LyFi firmware in Docker
      run: |
        docker run -t -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" -w "/app/${{ github.repository }}/fw/lyfi" espressif/idf:v5.4 /bin/bash -c 'git config --global --add safe.directory "*" && idf.py build'

#    - name: Build Doser firmware in Docker
#      run: |
#        docker run -t -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" -w "/app/${{ github.repository }}/fw/doser" espressif/idf:v5.4 /bin/bash -c 'git config --global --add safe.directory "*" && idf.py build'
